name: Build OpenSSL for macOS (arm64 + Intel)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  version: 1.1.1m
  sha256sum: f89199be8b23ca45fc7cb9f1d8d3ee67312318286ad030f5316aca6462db6c96

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Build OpenSSL
        uses: ./.github/workflows/openssl-mac
        with:
          version: ${{ env.OPENSSL_VER }}
          sha256sum: ${{ env.sha256sum }}

